### ISSUE TITLE
There is a problem when I am running train_predictor.py. How can I fix it?

### ISSUE THREAD

**Issue by jackfrost168** [co9olguy/Generating-and-designing-DNA#1]
OSError: /data/houyu/Generating-and-designing-DNA-master/data/data/train_vals.txt not found.

**Comment by co9olguy** [comment]
The code does not provide any datasets itself. You will have to create the training data (`train_vals.txt`) yourself and modify the scripts to be aware of the correct path

**Comment by jackfrost168** [comment]
> The code does not provide any datasets itself. You will have to create the training data (`train_vals.txt`) yourself and modify the scripts to be aware of the correct path

Thank you for your answer~~
